### ISSUE TITLE
kubelet与kube-scheduler写混

### ISSUE THREAD

**Issue by achuDk** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#10]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
664
## 问题描述
第二段原文：Kubernetes的kubelet通过计算Pod中所有容器的Requests的总和来决定对Pod的调度。
此处的kubelet与kube-scheduler是否写混了呢？我认为“调度”是对于pod等资源被调度到某个node来说的，kubelet只能管理本node的资源对象，无法修改资源对象的node。
我觉得应该改为：Kubernetes的kub-scheduler通过计算Pod中所有容器的Requests的总和来决定对Pod的调度。
## 相关链接

**Comment by kubeguide** [comment]
感谢指正！已更新至勘误文档
