### ISSUE TITLE
PV 受限于Namespace的说法不对

### ISSUE THREAD

**Issue by tanzhui** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#14]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
517页

## 问题描述
“注意，PVC和PV都受限于Namespace，PVC在选择PV时受到Namespace的限制，只有相同Namespace中的PV才可能与PVC绑定” 这一说法不对，PV 是集群资源，没有namespace属性，任何namespace都可以使用
参考官网说明：
low-level resources, such as nodes and persistentVolumes, are not in any namespace.

## 相关链接
官网说明链接：
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#not-all-objects-are-in-a-namespace

**Comment by kubeguide** [comment]
感谢指正！已更新至勘误文档。
