### ISSUE TITLE
448页 iptables-save显示的端口是59528，和下面描述的重定向端口33761不一致

### ISSUE THREAD

**Issue by seecsea** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#15]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 448

##下面半页， iptables-save显示的端口是59528，和下面描述的重定向端口33761不一致

## 无

**Comment by kubeguide** [comment]
感谢指正！已更新至勘误文档。
