### ISSUE TITLE
第一章中 myweb-rc.yaml 配置缺少部分

### ISSUE THREAD

**Issue by TomatoAres** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#16]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码

P10-11

## 问题描述

`myweb-rc.yaml` 缺少 MySQL 相关 env 配置

## 相关链接

[正确的配置](https://github.com/kubeguide/K8sDefinitiveGuide-V4-Sourcecode/blob/master/Chapter1/1.3.3%20myweb-rc.yaml)

**Comment by kubeguide** [comment]
已在勘误表第一条列出，谢谢

**Comment by fleeto** [comment]
其实这个是不缺的，系统自动生成的环境变量。
