### ISSUE TITLE
8页错误，demo代码

### ISSUE THREAD

**Issue by qinxiongzhou** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#21]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
8
## 问题描述
代码模块，image: mysql，实验后发现这个会拉去laster version，运行时有鉴权相关问题，为了demo简单起见，建议指定mysql版本，推荐使用image: mysql:5.6
## 相关链接

**Comment by kubeguide** [comment]
感谢您的反馈！
