### ISSUE TITLE
podAffinity 错误

### ISSUE THREAD

**Issue by Archer1A** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#22]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
198页
## 问题描述
nodeAffinity 规则第三条： 如果nodeSelectorTrems中有多个matchExpressions 则节点**必须满足所有**matchExpressions才能运行该Pod。 实际上只要满足之一便可调度，实验结果如此，官方文档也是这么说的
## 相关链接
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity

**Comment by vgbhfive** [comment]
If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node only if all matchExpressions is satisfied.
原文没有问题啊

**Comment by kubeguide** [comment]
原文逻辑是正确的。
感谢vgbhfive！
