### ISSUE TITLE
错将kafka-2.kafka写为kafka-3.kafka

### ISSUE THREAD

**Issue by MengLeebin** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#23]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
第37页

## 问题描述
则StatefulSet里的3个Pod的DNS名称为kafka-0.kafka、kafka-1.kafka、kafka-3.kafka，这些DNS名称可以直接在集群的配置文件中固定下来。

应该将 "Kafka-3.kafka” 改为 "kafka-2.kafka"

## 相关链接

**Comment by kubeguide** [comment]
感谢指正！
