### ISSUE TITLE
5.2.1 Replication Controller一节中存在部分错误描述

### ISSUE THREAD

**Issue by DMLayMan** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#24]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
P338

## 问题描述
对于资源对象的英文翻译也是Replication Controller，这部分存在着较大的误差。

## 相关链接

**Comment by kubeguide** [comment]
这部分内容在新版本中做了大幅修订，感谢指正！
