### ISSUE TITLE
650页计算资源的数字有问题

### ISSUE THREAD

**Issue by doudou673** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#25]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
650

## 问题描述
Capacity的memory，Allocated的memory，两组数字应该是反了。

## 相关链接

**Comment by kubeguide** [comment]
是Capacity中的memory数值有误，应为4016Mi，谢谢指正
