### ISSUE TITLE
1.4.9章节tomcat-service-multiple-ports.yaml内容问题

### ISSUE THREAD

**Issue by tomcyndi** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#29]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
40
## 问题描述
tomcat-service-multiple-ports.yaml的第7行至第10行，需往右再缩进两个空格，
否则执行kubectl create命令时，会提示解析错误：
`error: error parsing tomcat_multipleport.yaml: error converting YAML to JSON: yaml: line 7: did not find expected key`

## 相关链接

**Comment by kubeguide** [comment]
感谢指正！
应修改为：2个name左边补充1个空格
