### ISSUE TITLE
Kubernetes权威指南（第4版）3.9.9 Cronjob：定时任务DayofMonth取值范围描述错误

### ISSUE THREAD

**Issue by terryhy520** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#30]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
216页

## 问题描述
DayofMonth的有效范围为0~31的整数。
此处描述应该有误，正确的取值范围是1-31天。
## 相关链接
https://kubernetes.io/zh/docs/concepts/workloads/controllers/cron-jobs/

**Comment by kubeguide** [comment]
感谢指正！
