### ISSUE TITLE
Kubernetes权威指南（第4版）3.11.5 其他管理对象的更新策略 StatefulSet更新策略单词拼写错误

### ISSUE THREAD

**Issue by terryhy520** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#31]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
P239

## 错误描述
StatefulSet更新策略描述中，存在单词拼写错误
也将实现RollingUpdate、**Paritioned**、OnDelete
其中Paritioned拼写错误，正确应为：**Partitioned**
## 相关链接
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions

**Comment by kubeguide** [comment]
感谢指正！
