### ISSUE TITLE
Pod属性名称异常

### ISSUE THREAD

**Issue by Z-eddy** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#32]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题所在页码
151、155

## 问题描述
155页的livenessProbe的归属和151页的定义不一致

**Comment by kubeguide** [comment]
表格中的spec.volumes[].livenessProbe应改为spec.containers[].livenessProbe
感谢指正！
