### ISSUE TITLE
《K8s 权威指南》第4版-勘误反馈 - 210705

### ISSUE THREAD

**Issue by astraw99** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#34]
Hi Authors,
根据博文视点管理员邮件回复，找到了这里是提交勘误的地方，烦请更正以下错误(花了很多时间去记录、整理)，谢谢。
这是我进入 K8s 世界的第一本书籍，从中学到了很多，也看到有些内容已经 `Deprecated`，感谢作者们的心情付出。
祝再版错误更少，最新内容更多，越卖越好！

《K8s 权威指南》第4版-勘误列表：

1. page: 185 简写需要提前说明
中间：查看 dapi-xxx 日志：
k logs xxx => kubectl logs xxx

2. page: 357 单词错误
上面第 9 行：airpin-masquerade => hairpin-masquerade

3. page: 367 汉字错误
上面第 2 行：“运行访问” => “允许访问”

4. page: 385 单词错误
上面第 8 行：EventReateLimit => EventRateLimit

5. page: 390 单词错误
图中：Service Account->Tokens/Secret->两处TOCKEN => TOKEN

6. page: 393 单词错误
下半部分倒数第 10 行：（3）通过指定 Pod spc => spec

7. page: 394 单词错误
图中：TOCKEN => TOKEN

8. page: 401 设置 Group 不是 User
上半部分：（2）RunAsGroup: 第二点 MustRunAsNonRoot: securityContext
runAsUser 设置一个非 0 的用户 ID  => runAsGroup 设置一个非0 的 Group ID

9. page: 414 中文字错误
中间部分：所有网站栈变量 => 所有网络栈变量

10. page: 416 编号有误
下面图片：右边 Namespace1 => Namespace2

11. page: 427 拼写错误
上面部分第四行：RPC1918 => RFC 1918(中间有空格)

12. page: 441 gw 错误
中间部分路由项：
gw 192.168.130 => gw 192.168.1.130
gw 192.168.131 => gw 192.168.1.131

13. page: 515 单词错误
底部倒数第二行：4个阶段（phaes）=> phase

14. page: 516 单复数错误
底部倒数第四行：request.storage => requests.storage

15. page: 538 单词错误
上面部分：“in-true”（树内）=> “in-tree”（树内）

16. page: 571 冒号改为 /
下半部分：apiVersion: extensions:v1beta1 => apiVersion: extensions/v1beta1

17. page: 590 单词大写、单数
最后一行：PersistentVolumeclaims => PersistentVolumeClaim

18. page: 598
下半部分：Fabric8 框架代码 IP 与 port 之间没有空格
"http://192.168.1.128: 8080" => "http://192.168.1.128:8080"

19. page: 621 单词错误
上面部分：stcatus => status

P.S. 可以建立一个读书反馈社群，方便有不懂的地方或勘误，可以及时提交反馈。
以上如是，盼复。

**Comment by kubeguide** [comment]
非常感谢您细致的指正，已更新到“勘误.txt”中。

另外，目前有3个QQ群：285431657、562570318、678983776，欢迎交流。

**Comment by astraw99** [comment]
> 非常感谢您细致的指正，已更新到“勘误.txt”中。
> 
> 另外，目前有3个QQ群：285431657、562570318、678983776，欢迎交流。

好的，谢谢。目前加了一个群，前几天在群里催了管理员 issue 两个多月都没回复，可能才联系到您这边了。
期望书籍更新的更加及时、完善，让更多人受益~
