### ISSUE TITLE
勘误中的疑问

### ISSUE THREAD

**Issue by shawn0915** [kubeguide/K8sDefinitiveGuide-V4-corrigendum#35]
## 书名

- [x] Kubernetes 权威指南（第四版）

## 问题描述

39. 第155-156页：表格中的spec.volumes[].livenessProbe 应改为 spec.containers[].livenessProbe
应该为 第154-155页

我的书版次为2019年6月第4版，2019年12月第5次印刷

## 相关链接

https://github.com/kubeguide/K8sDefinitiveGuide-V4-corrigendum/blob/master/%E5%8B%98%E8%AF%AF.txt#L106

**Comment by kubeguide** [comment]
在修订版中已修正，感谢指正！
